[[redirects]]
  from = "/api/*"
  to = "http://digital.devkayy.in/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "http://digital.devkayy.in/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
